name: Auto with manual approval

on:
  # auto on push
  push:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: hello
        run: echo Hello, world!

  manual-job:
    needs: build
    # based on https://stackoverflow.com/a/73708545/1016377
    # there is a "test-approvers" in settings>environment with required approvers
    environment:
      name: test-approvers
    runs-on: ubuntu-latest
    steps:
      - name: hello again, manual
        run: echo "manual-job triggered"
